#!/usr/bin/env bash

echo applying secrets...
kubectl apply -f ./k8s/secret.yaml
echo applying db manifest...
kubectl apply -f ./k8s/pst-db.yaml
echo applying api manifest...
kubectl apply -f ./k8s/pst-api.yaml
echo applying apiweb manifest...
kubectl apply -f ./k8s/pst-apiweb.yaml
echo applying web manifest...
kubectl apply -f ./k8s/pst-web.yaml
echo applying cron manifest...
kubectl apply -f ./k8s/pst-cron.yaml