#!/usr/bin/env bash

echo applying secrets...
kubectl apply -f secret.yaml
echo applying db manifest...
kubectl apply -f pst-db.yaml
echo applying api manifest...
kubectl apply -f pst-api.yaml
echo applying apiweb manifest...
kubectl apply -f pst-apiweb.yaml
echo applying web manifest...
kubectl apply -f pst-web.yaml
echo applying cron manifest...
kubectl apply -f pst-cron.yaml